// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var chai, expect;

  chai = require('chai');

  chai.use(require('chai-as-promised'));

  expect = chai.expect;

  module.exports = {
    selenium_instance: function(spec, specSet) {
      var _, subject, type;
      subject = specSet.code[specSet.methodName];
      type = typeof subject;
      if (type === 'function') {
        subject.apply(specSet.code, spec.input);
      }
      return _ = {
        actual: typeof specSet.code[specSet.methodName],
        expected: spec.expected
      };
    },
    selenium_text_by_selector: function(code, i, e) {
      var text;
      text = code.use.findElement({
        css: i
      }).getText();
      return expect(text).to.eventually.equal(e);
    },
    selenium_text: function(code, i, e) {
      var text;
      text = code.use.findElement(i).getText();
      return expect(text).to.eventually.equal(e);
    }
  };

}).call(this);
